services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    container_name: routermini-db
    restart: always
    environment:
      POSTGRES_DB: routermini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: